### ISSUE TITLE
System crashes when awaking from sleep with external keyboard connected

### ISSUE THREAD

**Issue by iyee** [tekezo/Karabiner#431] opened 2015-07-03 01:19 UTC
env: 10.11 DP2/Karabiner 10.6.75/HHKB Pro

```
Anonymous UUID:       AD3E3EC9-76B0-7C2B-7CC8-5A7DD711BC1C

Fri Jul  3 09:16:11 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff80151d67aa): Kernel trap at 0xffffff7f95fec456, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x00000000182a4000, CR4: 0x00000000001627e0
RAX: 0xffffff8034574440, RBX: 0xffffff7f9600e5a8, RCX: 0x000000000000fc00, RDX: 0x0000000000000001
RSP: 0xffffff9224f43c20, RBP: 0xffffff9224f43dc0, RSI: 0x0000000000000000, RDI: 0x0000000000000000
R8:  0xffffff8033c7e000, R9:  0x0000000000000001, R10: 0x0000000000000000, R11: 0x0000000000000021
R12: 0x0000000000000001, R13: 0xffffff803420bd00, R14: 0xffffff81fee50000, R15: 0x0000000000000002
RFL: 0x0000000000010246, RIP: 0xffffff7f95fec456, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0

Backtrace (CPU 0), Frame : Return Address
0xffffff9224f438b0 : 0xffffff80150e73b7 
0xffffff9224f43930 : 0xffffff80151d67aa 
0xffffff9224f43b10 : 0xffffff80151f3cc3 
0xffffff9224f43b30 : 0xffffff7f95fec456 
0xffffff9224f43dc0 : 0xffffff7f95ff18bb 
0xffffff9224f43e20 : 0xffffff7f95ff1d3b 
0xffffff9224f43ea0 : 0xffffff80156bb2f3 
0xffffff9224f43f00 : 0xffffff801511adaa 
0xffffff9224f43fb0 : 0xffffff80151d11e7 
      Kernel Extensions in backtrace:
         com.apple.driver.usb.AppleUSBXHCI(1.0.1)[1076DBB1-9519-30C3-9E5C-251BAB1C7B1B]@0xffffff7f95fe1000->0xffffff7f96019fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[CBAE26D8-0ACB-3C1F-8347-FDCA67EC40B3]@0xffffff7f95fd8000
            dependency: com.apple.iokit.IOUSBHostFamily(1.0.1)[CAE2E630-91E2-3A3D-9364-22D6C04AC9CA]@0xffffff7f95de2000

BSD process name corresponding to current thread: kernel_task

Mac OS version:
15A204h

Kernel version:
Darwin Kernel Version 15.0.0: Wed Jun 17 21:18:51 PDT 2015; root:xnu-3247.1.6.2.2~1/RELEASE_X86_64
Kernel UUID: 266D095F-9DB4-3CC4-A89F-53D51D20218C
Kernel slide:     0x0000000014e00000
Kernel text base: 0xffffff8015000000
__HIB  text base: 0xffffff8014f00000
System model name: MacBookPro11,1 (Mac-189A3D4F975D5FFC)

System uptime in nanoseconds: 90222359058562
last loaded kext at 79960119580669: com.apple.filesystems.exfat	1.4 (addr 0xffffff7f97b7d000, size 65536)
last unloaded kext at 22199676207232: com.parallels.kext.hypervisor	10.2.1 29006 (addr 0xffffff7f97b63000, size 319488)
loaded kexts:
org.pqrs.driver.Karabiner	10.6.75
org.virtualbox.kext.VBoxNetAdp	4.3.28
org.virtualbox.kext.VBoxNetFlt	4.3.28
org.virtualbox.kext.VBoxUSB	4.3.28
org.virtualbox.kext.VBoxDrv	4.3.28
com.apple.filesystems.exfat	1.4
com.apple.filesystems.afpfs	11.0
com.apple.nke.asp-tcp	8.0.0
com.apple.filesystems.smbfs	3.0.0
com.apple.driver.AppleBluetoothMultitouch	90.2
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AGPM	110.20.19
com.apple.driver.ApplePlatformEnabler	2.5.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleHDAHardwareConfigDriver	272.36
com.apple.driver.AppleGraphicsDevicePolicy	3.7.7
com.apple.driver.AppleHDA	272.36
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.pmtelemetry	1
com.apple.driver.LuaHardwareAccess	1.0.0d13
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	4.4.0d72
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleMuxControl	3.11.25
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.4.0d72
com.apple.driver.AppleSMCLMU	208
com.apple.driver.AppleBacklight	170.8.1
com.apple.driver.AppleMCCSControl	1.2.13
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.iokit.IOBluetoothUSBDFU	4.4.0d72
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleThunderboltIP	3.0.5
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleCameraInterface	5.36.0
com.apple.driver.AppleIntelHD5000Graphics	10.0.8
com.apple.driver.AppleIntelFramebufferAzul	10.0.8
com.apple.driver.AppleUSBTCButtons	245.4
com.apple.iokit.SCSITaskUserClient	3.7.7
com.apple.driver.AppleUSBCardReader	3.6.0
com.apple.driver.AppleUSBTCKeyEventDriver	245.4
com.apple.driver.AppleUSBTCKeyboard	245.4
com.apple.driver.CoreStorageFsck	507
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	37
com.apple.iokit.IOAHCIBlockStorage	2.8.0
com.apple.driver.AppleAHCIPort	3.1.5
com.apple.driver.AirPort.Brcm4360	1000.8.2a3
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	4.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	4.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	163
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.security.SecureRemotePassword	1.0
com.apple.driver.IOBluetoothHIDDriver	4.4.0d72
com.apple.driver.AppleMultitouchDriver	304.2
com.apple.driver.AppleHIDTransport	1.7
com.apple.iokit.IOUSBUserClient	900.4.1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	272.36
com.apple.kext.OSvKernDSPLib	525
com.apple.driver.AppleGraphicsControl	3.11.25
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.4.0d72
com.apple.iokit.IOBluetoothFamily	4.4.0d72
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.CoreCaptureResponder	1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleHDAController	272.36
com.apple.iokit.IOHDAFamily	272.36
com.apple.iokit.IOAudioFamily	203.7
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleThunderboltEDMSink	4.1.1
com.apple.driver.AppleThunderboltDPOutAdapter	4.1.2
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.IOPlatformPluginFamily	6.0.0d7
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.driver.AppleIntelLpssUART	2.0.57
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOSurface	106
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.AppleGraphicsDeviceControl	3.11.25
com.apple.iokit.IOAcceleratorFamily2	201.0.0
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.usb.IOUSBHostHIDDevice	1.0.1
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.7
com.apple.iokit.IOUSBMassStorageDriver	1.0.0
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.7
com.apple.driver.AppleUSBMultitouch	250.4
com.apple.iokit.IOUSBHIDDriver	900.4.1
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.0.1
com.apple.driver.usb.AppleUSBHub	1.0.1
com.apple.driver.CoreStorage	507
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IOAHCIFamily	2.8.0
com.apple.driver.AppleThunderboltDPInAdapter	4.1.2
com.apple.driver.AppleThunderboltDPAdapterFamily	4.1.2
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.driver.AppleThunderboltNHI	4.0.1
com.apple.iokit.IOThunderboltFamily	5.0.4
com.apple.iokit.IO80211Family	1100.15.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleIntelLpssGspi	2.0.57
com.apple.driver.AppleIntelLpssDmac	2.0.57
com.apple.driver.AppleIntelLpssI2C	2.0.57
com.apple.driver.usb.AppleUSBXHCIPCI	1.0.1
com.apple.driver.usb.AppleUSBXHCI	1.0.1
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleUSBMergeNub	900.4.1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	413
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.iokit.IOUSBHostFamily	1.0.1
com.apple.driver.AppleUSBHostMergeProperties	1.0
com.apple.driver.AppleACPIPlatform	4.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
Model: MacBookPro11,1, BootROM MBP111.0138.B15, 2 processors, Intel Core i5, 2.6 GHz, 16 GB, SMC 2.16f68
Graphics: Intel Iris, Intel Iris, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.21.63.0.2a3)
Bluetooth: Version 4.4.0d72 15995, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Card Reader
USB Device: USB3.0 Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB2.0 Hub
USB Device: Hub
USB Device: HHKB Professional
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.2
```

**Comment by tekezo** [comment] 2015-07-03 03:23
Thank you for feedback.
Does this issue always reproduce?

**Comment by iyee** [comment] 2015-07-03 03:34
it lasts for several beta builds & can be reproduced.

**Comment by tekezo** [comment] 2015-07-03 16:14
I cannot reproduce this issue.
I doubt it's an issue of OS X.
Will this issue disappear if you uninstall Karabiner?

**Comment by iyee** [comment] 2015-07-06 01:41
Downgraded to 10.6.0 stable & it works well.

**Comment by tekezo** [comment] 2015-07-06 05:57
Thank you for confirmation.
I continue trying to reproduce this issue.

And I want to know the version which this issue has been introduced.
Do you have other crash reports in previous Karabiner version? (eg. v10.6.69)

**Comment by iyee** [comment] 2015-07-06 06:28
Sorry, I didn't save them all.

**Comment by tekezo** [comment] 2015-07-06 16:46
Unfortunately, I still cannot reproduce this issue.
Could you help me to find the change that introduced a bug?

There are the recent versions that changes kernel extension which might cause a crash.

V10.6.56 https://pqrs.org/macosx/karabiner/files/Karabiner-10.6.56.dmg
v10.6.60 https://pqrs.org/macosx/karabiner/files/Karabiner-10.6.60.dmg
v10.6.64 https://pqrs.org/macosx/karabiner/files/Karabiner-10.6.64.dmg
v10.6.67 https://pqrs.org/macosx/karabiner/files/Karabiner-10.6.67.dmg
v10.6.69 https://pqrs.org/macosx/karabiner/files/Karabiner-10.6.69.dmg
v10.6.75 https://pqrs.org/macosx/karabiner/files/Karabiner-10.6.75.dmg

Please confirm whether v10.6.56 works well.
If it works well, we can concentrate between v10.6.56 and v10.6.75.

**Comment by iyee** [comment] 2015-07-07 02:02
OK, I'm going to test them one by one, stay tuned.

**Comment by tekezo** [comment] 2015-07-07 03:28
I appreciate your help!

**Comment by iyee** [comment] 2015-07-13 05:46
current progress: 10.6.56-10.6.64 cannot reproduce the problem.

**Comment by tekezo** [comment] 2015-07-13 06:13
Thank you!

I adjusted a code which has changed in v10.6.64 - v10.6.75.
Could you confirm the latest beta version (v10.6.81)?

**Comment by iyee** [comment] 2015-07-15 01:14
Can't reproduce the kernel panic on 10.6.81, cheers.

**Comment by tekezo** [comment] 2015-07-15 02:19
Thank you for confirmation!
I close this issue. Please reopen if this issue will be reproduced.

**Closed by tekezo** 2015-07-15 02:19 UTC
